apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: nexus-operator-m88i
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: m88i
  displayName: "Nexus Operator"
  publisher: "m88i Labs"
