apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus-operator
  template:
    metadata:
      labels:
        name: nexus-operator
    spec:
      serviceAccountName: nexus-operator
      containers:
        - name: nexus-operator
          image: quay.io/m88i/nexus-operator:0.4.0-cr1
          command:
            - nexus-operator
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nexus-operator"
